Tool testing changes
Tumo-Product/Story_Board_Plugin pull request #10
Opened 2022-07-06 13:24 UTC by vrezhMik

Here should be only one commit. I don't know why is placeholder commit in here. And merge commit is so weird. I couldn't understand what is that.

2022-07-06 13:58 UTC, tumochristine requested changes

2022-07-06 13:58 UTC, tumochristine commented on src/Store.vue
> +  remove_object: (event) => {
This event variable doesn't seem to be used, and it's throwing a compilation error. Is it needed?

2022-07-06 13:58 UTC, tumochristine commented on src/components/FlipButtons.vue
> +    object.rotate_y = object.rotate_y == 180 ? 0 : 180;
I forgot to mention this in your last CR, but it's better practice to use "===" instead of "=="

2022-07-06 13:58 UTC, tumochristine commented on src/components/RotateButtons.vue
> +  if (object.rotate_y && object.rotate_x) object.rotate_z += -15;
What does this mean?

2022-07-06 13:58 UTC, tumochristine commented on src/components/RotateButtons.vue
> +        : 15;
This is a bit too long, it's hard to read. Can you break it down into multiple lines, with separate variables?

2022-07-07 07:03 UTC, vrezhMik commented on src/Store.vue
> +  remove_object: (event) => {
Already removed

2022-07-07 07:04 UTC, vrezhMik commented on src/components/FlipButtons.vue
> +    object.rotate_y = object.rotate_y == 180 ? 0 : 180;
Changed it everywhere

2022-07-07 07:05 UTC, vrezhMik commented on src/components/RotateButtons.vue
> +  if (object.rotate_y && object.rotate_x) object.rotate_z += -15;
This is for rotation in case the object has been flipped both in vertical and horizontal way so it still will rotate in proper direction.

2022-07-07 07:06 UTC, vrezhMik commented on src/components/RotateButtons.vue
> +        : 15;
The part in braces is not necessary. I will remove it

2022-07-12 09:07 UTC, tumochristine requested changes

2022-07-12 09:07 UTC, tumochristine commented on src/components/RotateButtons.vue
> +        : 15;
This needs to be addressed

2022-07-12 10:38 UTC, tumochristine approved these changes

2022-07-12 10:39 UTC, merged