Change view and some functionality
Tumo-Product/Story_Board_Plugin pull request #2
Opened 2022-05-25 07:43 UTC by vrezhMik

Frame with 6 boards is apperaing at the beggingin. After clicking on any of boards canvas will be shown.

2022-06-21 14:59 UTC, tumochristine requested changes
Great stuff Vrezh! I love the new tool

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/FirstFrame.vue
> +    v-if="Store.animate_button.value && !Store.start.value"
Hmm what does animate_button really stand for? Can we find a better name for it?

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/FirstFrame.vue
> +    <div class="first_fram_content">
*first_frame_content

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/FirstFrame.vue
> +    :class="{ show: Store.animate_button.value }"
Instead of showing and hiding this component using CSS classes, you can show and hide it based on the `v-if` in `StartFrame.vue`. This way, Vue will actually not render the component when it's not needed.

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/FlipButtons.vue
> +<script setup></script>
Maybe add a todo either here or in the parent component to implement these image actions?

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/ImageObject.vue
> +  <img :src="object.img" alt="" />
what is object.img?

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/ImageObject.vue
> +// let scale = object.scale
remove commented code

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/ObjectBoard.vue
> +<template>
How are you testing this functionality?

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/ViewBoard.vue
> +<template>
We can rename this component "BoardOverview" to make it clearer

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/ViewButton.vue
> +    :class="{ show: Store.edit_mode }"
Show/hide using `v-if` on parent instead

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/PreviewBoards.vue
> +  /* justify-content: space-between;
remove comments if not necessary

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/SaveButton.vue
> +      @click="save"
This might be more a question for Raz, but I would expect that clicking anywhere in the toggle (anywhere in `save_button`) would switch it. Currently, you have to click on the check mark to switch it.

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/SaveButton.vue
> +  Store.saved_status.value = !Store.saved_status.value;
Add a TODO here to add save functionality

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/StartFrame.vue
> +    <!-- Change class names!!!-->
Change class names!!! :D

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/StartFrame.vue
> +      <div class="tool_name" :class="{ hide: Store.animate_button.value }">
You can use v-if instead of the CSS classname to render the component

2022-06-21 14:59 UTC, tumochristine commented on src/viewer/components/StartFrame.vue
> +//Testing values need to be deleted
is first_usage ever false? Should this stuff be deleted

2022-06-21 14:59 UTC, tumochristine commented on vue.config.js
> +  publicPath: './'
Do we want to do this yet, or will it publish this project before it's ready?

2022-06-22 07:04 UTC, vrezhMik commented on src/App.vue
> -</style>
It is not necessary. I removed this file and changed path in main.js

2022-06-22 07:04 UTC, vrezhMik commented on src/Store.vue
> +    { name: "objcets", state: ref(false) },
changed

2022-06-22 07:05 UTC, vrezhMik commented on src/viewer/components/ViewBoard.vue
> +          :class="{ empty_board: !Store.boards[story]['objcets'] }"
changed

2022-06-22 07:06 UTC, vrezhMik commented on src/Store.vue
> +        activityId: "dev",
Hayk made backend part of the tool. We used dev just for the beginning. Then there going to be activity id

2022-06-22 07:06 UTC, vrezhMik commented on src/components/HelloWorld.vue
> +      For a guide and recipes on how to configure / customize this project,<br>
Removed. It is template file which comes at the creation of the project.

2022-06-22 07:08 UTC, vrezhMik commented on src/junk.vue
> +<script>
I am using this file just for testing. It is blank file which is going to be removed at the end.

2022-06-22 07:08 UTC, vrezhMik commented on src/junk.vue
> +  console.log(event.clientX - start.value, startingLeft);
clean

2022-06-22 07:08 UTC, vrezhMik commented on src/junk.vue
> +if (
clean

2022-06-22 07:09 UTC, vrezhMik commented on src/junk.vue
> +  (startingLeft == -3510 && +(event.clientX - start.value) > 0) ||
clean

2022-06-22 07:09 UTC, vrezhMik commented on src/viewer/components/DeleteButton.vue
> +    <button class="delete">
I just made the component but not this functionality yet

2022-06-22 07:09 UTC, vrezhMik commented on src/viewer/components/DeleteButton.vue
> +/* .delete:hover svg {
done

2022-06-22 07:10 UTC, vrezhMik commented on src/viewer/components/DeleteButton.vue
> +<script setup></script>
Going to work on its algorythm

2022-06-22 07:10 UTC, vrezhMik commented on src/viewer/components/DeleteButton.vue
> +<style>
done

2022-06-22 07:11 UTC, vrezhMik commented on src/viewer/components/EditBoard.vue
> +    <div class="categories">
I put it inside the component

2022-06-22 07:13 UTC, vrezhMik commented on src/viewer/components/EditBoard.vue
> +.edit_description {
In InputFrame.vue I have a textarea and div. I keep only their stylings init

2022-06-22 07:14 UTC, vrezhMik commented on src/viewer/components/EditBoard.vue
> +.edit_description {
Done

2022-06-22 07:14 UTC, vrezhMik commented on src/viewer/components/EditBoard.vue
> +      <div class="edit_description">
Done

2022-06-22 07:14 UTC, vrezhMik commented on src/viewer/components/EditBoard.vue
> +<script setup>
Can I keep it how i have it now?

2022-06-22 07:15 UTC, vrezhMik commented on src/viewer/components/EditBoard.vue
> +.categories_types {
done

2022-06-22 07:16 UTC, vrezhMik commented on src/viewer/components/EditBoard.vue
> +.categories_assets {
will do

2022-06-22 07:17 UTC, vrezhMik commented on src/viewer/components/EditFrameCategories.vue
> +<template>
done

2022-06-22 07:19 UTC, vrezhMik commented on src/viewer/components/EditFrameCategories.vue
> +  <div class="categories_assets">
done

2022-06-22 07:19 UTC, vrezhMik commented on src/viewer/components/EditButtons.vue
> +<template>
done

2022-06-22 07:20 UTC, vrezhMik commented on src/viewer/components/EditFrameCategories.vue
> +  <div class="categories_types">
yes. it used as a parent div

2022-06-22 07:21 UTC, vrezhMik commented on src/viewer/components/EditFrameCategories.vue
> +      class="type"
done

2022-06-22 07:24 UTC, vrezhMik commented on src/viewer/components/FirstFrame.vue
> +    <div class="first_fram_content">
done

2022-06-22 07:25 UTC, vrezhMik commented on src/viewer/components/FirstFrame.vue
> +    :class="{ show: Store.animate_button.value }"
It has css animation in that class. That is why I am showing it with a class

2022-06-22 07:27 UTC, vrezhMik commented on src/viewer/components/ImageObject.vue
> +  <img :src="object.img" alt="" />
Object is curent object and object.img keeps its img href. I will change it to object.href

2022-06-22 07:28 UTC, vrezhMik commented on src/viewer/components/ImageObject.vue
> +// let scale = object.scale
done

2022-06-22 07:31 UTC, vrezhMik commented on src/viewer/components/ViewButton.vue
> +<template>
done

2022-06-22 07:33 UTC, vrezhMik commented on src/viewer/components/PreviewBoards.vue
> +      v-for="story in Object.keys(Store.boards.value).length"
done

2022-06-22 07:33 UTC, vrezhMik commented on src/viewer/components/PreviewBoards.vue
> +  /* justify-content: space-between;
done

2022-06-22 07:34 UTC, vrezhMik commented on src/viewer/components/SaveButton.vue
> +      @click="save"
I am not actualy done with save. So I will look at it again

2022-06-22 07:35 UTC, vrezhMik commented on src/viewer/components/StartFrame.vue
> +//Testing values need to be deleted
Will look through it again

2022-06-22 07:36 UTC, vrezhMik commented on vue.config.js
> +  publicPath: './'
it is just change of path. It is not have any problems

2022-06-22 08:54 UTC, tumochristine requested changes
Also please rename your pull request and add a description to it. And add a REAME that includes instructions on getting the project up and running

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/StoryPreview.vue
> +let startingLeft;
Let's move this into the `toggle_mouse` function

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/DeleteButton.vue
> +    <button class="delete">
Then let's leave `TODO` comments in the code

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/DeleteButton.vue
> +<script setup></script>
In general, you shouldn't commit something to the codebase until it's working. But if you want to keep this, add a `TODO`, so you won't forget it in this state

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/DeleteButton.vue
> +<style>
There are still a lot of places that are using the unscoped `<style>`

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/EditBoard.vue
> +<script setup>
Sure

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/EditBoard.vue
> +.categories_assets {
It seems like there are a few still left, for example `categories_assets` is still partially styled in `ImageCategories.vue`

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/EditFrameCategories.vue
> +      Store.current_category.value = id;
^

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/FirstFrame.vue
> +    v-if="Store.animate_button.value && !Store.start.value"
^

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/FirstFrame.vue
> +    :class="{ show: Store.animate_button.value }"
This is the standard way to do transitions in vue: https://v2.vuejs.org/v2/guide/transitions.html

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/ObjectBoard.vue
> +<template>
^

Same with testing all of the image actions, how are you testing them? I can't currently add any of the images to the main scene, so I can't really test the tool

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/EditButtons.vue
> +  <div class="edit_buttons">
^

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/PreviewBoards.vue
> +  /* justify-content: space-between;
There are still some comments left, search your codebase for "/*" to find them

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/SaveButton.vue
> +      @click="save"
Add it as a TODO so you don't forget

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/SaveButton.vue
> +  Store.saved_status.value = !Store.saved_status.value;
Add TODO to not forget

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/StartFrame.vue
> +//Testing values need to be deleted
^

2022-06-22 08:54 UTC, tumochristine commented on vue.config.js
> +  publicPath: './'
Ok, as long as you're sure

2022-06-22 08:54 UTC, tumochristine commented on src/viewer/components/StartFrame.vue
> +<template>
This isn't really the "starting frame", it's more like the entire tool, so let's rename to "Tool" or "Widget" or something more accurate

2022-06-22 09:01 UTC, tumochristine commented
I just tested the tool by adding several images and playing around with them. It's awesome! Some issues I found:

- the delete button doesn't work
- the two buttons in the middle (i think they're move up and move down?) don't work
- none of the buttons have alt text, so if a student tried to hover over them to understand what they do, no text shows up
- previewing the story currently seems to be broken
- when i edit a scene, then go to the overview, the thumbnail isn't updated
- going left and right through the editing scenes doesn't show the correct scene
- sometimes things stay selected (surrounded by a red line) even when I try to click something else

2022-06-23 14:24 UTC, vrezhMik commented on src/Store.vue
> +        activityId: "dev",
done

2022-06-23 14:26 UTC, vrezhMik commented on src/viewer/components/EditBoard.vue
> +.categories_assets {
done

2022-06-23 14:30 UTC, vrezhMik commented on src/viewer/components/EditButtons.vue
> +  <div class="edit_buttons">
Functionality is added

2022-06-23 14:37 UTC, vrezhMik commented on src/viewer/components/PreviewBoards.vue
> +  /* justify-content: space-between;
all comments removed

2022-06-23 14:38 UTC, vrezhMik commented on src/viewer/components/SaveButton.vue
> +      @click="save"
done

2022-06-23 14:39 UTC, vrezhMik commented on src/viewer/components/StartFrame.vue
> +      <div class="tool_name" :class="{ hide: Store.animate_button.value }">
done

2022-06-23 14:39 UTC, vrezhMik commented on src/junk.vue
> +
removed

2022-06-23 14:40 UTC, vrezhMik commented on src/viewer/components/SaveButton.vue
> +  Store.saved_status.value = !Store.saved_status.value;
done

2022-06-23 16:15 UTC, vrezhMik commented on src/viewer/components/FirstFrame.vue
> +    v-if="Store.animate_button.value && !Store.start.value"
I removed animated button

2022-06-23 16:16 UTC, vrezhMik commented on src/viewer/components/StartFrame.vue
> +    <!-- Change class names!!!-->
done

2022-06-23 16:27 UTC, vrezhMik commented on src/viewer/components/StartFrame.vue
> +//Testing values need to be deleted
This value will be changed when i add ActivityManager API

2022-06-27 08:35 UTC, tumochristine commented on src/viewer/components/SaveButton.vue
> +      @click="save"
Where is the TODO? I don't see it. Did you ask Raz about changing the button to the more expected format?

2022-06-27 08:36 UTC, tumochristine commented on src/viewer/components/SaveButton.vue
> +  Store.saved_status.value = !Store.saved_status.value;
I don't see a TODO?

2022-06-27 08:37 UTC, tumochristine commented
I unresolved the comments that you had resolved but not addressed. If you refresh this page, you should see them

Nice work fixing all the bugs I pointed out last time! There are a couple more I noticed:
The two to_top and to_bottom buttons still don’t work
You can’t drag one foreground asset over another
I still see a bunch of components being rendered when they shouldn’t be. You shouldn’t need the “show/hide” cases now

2022-06-27 08:52 UTC, vrezhMik commented on src/viewer/components/DeleteButton.vue
> +<style>
All styles are scoped except style in .viewer/App.vue I keep global stylings there such as fonts and main stylings

2022-06-27 10:52 UTC, vrezhMik commented on src/viewer/components/SaveButton.vue
> +  Store.saved_status.value = !Store.saved_status.value;
Todo added

2022-06-27 11:06 UTC, vrezhMik commented on src/viewer/components/EditFrameCategories.vue
> +      Store.current_category.value = id;
I removed categor.state.value = true

2022-06-27 11:12 UTC, vrezhMik commented on src/viewer/components/FirstFrame.vue
> +    :class="{ show: Store.animate_button.value }"
done

2022-06-27 11:12 UTC, vrezhMik commented on src/viewer/components/ArrowButtons.vue
> +    :class="{ show: Store.edit_mode }"
done

2022-06-27 11:12 UTC, vrezhMik commented on src/viewer/components/SaveButton.vue
> +    :class="{ show: Store.view_mode }"
done

2022-06-27 11:12 UTC, vrezhMik commented on src/viewer/components/SaveButton.vue
> +      @click="save"
Done

2022-06-27 11:13 UTC, vrezhMik commented on src/viewer/components/StoryPreview.vue
> +let startingLeft;
done

2022-06-27 13:20 UTC, vrezhMik commented on src/viewer/components/EditFrameCategories.vue
> +      Store.current_category.value = id;
I wrote it back because I use it to set the choosed button

2022-06-28 10:51 UTC, vrezhMik commented on src/junk.vue
> +  console.log(event.clientX - start.value, startingLeft);
removed

2022-06-28 10:51 UTC, vrezhMik commented on src/junk.vue
> +if (
removed

2022-06-28 10:52 UTC, vrezhMik commented on src/junk.vue
> +  (startingLeft == -3510 && +(event.clientX - start.value) > 0) ||
removed

2022-06-28 10:52 UTC, vrezhMik commented on src/junk.vue
> +      console.log(event.clientX - start.value, startingLeft);
removed

2022-06-28 10:53 UTC, vrezhMik commented on src/viewer/components/DeleteButton.vue
> +<script setup></script>
Script is added

2022-06-29 07:35 UTC, tumochristine approved these changes
Looks good to me (LGTM).

2022-06-29 07:48 UTC, merged