Changed Nested Images structure
Tumo-Product/Story_Board_Plugin pull request #5
Opened 2022-06-29 12:25 UTC by vrezhMik

Fix slow image loading

Currently, all of the nested asset images are loading at once, which makes them load very slowly for the user. Let's fix this by changing the structure so that only the visible images are loaded. Once the user clicks on the show button, the rest of the images will be loaded

2022-06-29 13:06 UTC, tumochristine requested changes
Nice improvement! Let's change the commit message to be a bit clearer and more informative. Maybe something like:

"Fix slow image loading

Currently, all of the nested asset images are loading at once, which makes them load very slowly for the user. Let's fix this by changing the structure so that only the visible images are loaded. Once the user clicks on the show button, the rest of the images will be loaded"

2022-06-29 13:06 UTC, tumochristine commented on src/viewer/components/GroupedAssets.vue
> +  let objcet_id = new Date().getTime();
*object

2022-06-29 13:09 UTC, vrezhMik commented on src/viewer/components/NestedImages.vue
> +      :assets="props.loop.slice(1, props.loop.length - 1)"
it takes all except the first one

2022-06-29 13:10 UTC, vrezhMik commented on src/viewer/components/NestedImages.vue
> +  else if (show_assets.value) {
it is reactive variable thats why it needs value. otherwise it will be a promise or something like that

2022-06-29 13:11 UTC, vrezhMik commented on src/viewer/components/GroupedAssets.vue
> +  let objcet_id = new Date().getTime();
changed!

2022-06-29 13:19 UTC, tumochristine commented on src/viewer/components/NestedImages.vue
> +      :assets="props.loop.slice(1, props.loop.length - 1)"
Are you sure? I tested it out on an array and it excludes the last element

<img width="207" alt="Screen Shot 2022-06-29 at 5 18 55 PM" src="https://user-images.githubusercontent.com/102517998/176446067-947dca26-fd87-4136-a0b6-04bb89b37476.png">

2022-06-30 10:49 UTC, HaykAvagyan1 requested changes
There were a lot of changes here which were not related to Changing nested images structure, keep pull requests one commit (unless you need to add fixes with a new commit) or just one manageable block of work so it's easier to review.
Also reword `CR changes` commit, because it's not just code review changes, it's changing and adding a bunch of stuff, also add a description to it so it's easier to understand what that commit is doing.

Address the comments and we're ready to merge!

2022-06-30 10:49 UTC, HaykAvagyan1 commented on src/examiner/components/StoryPreview.vue
> +<script setup>
We were working on this file last week or even earlier I believe, why is it added as a fresh new file in this commit?

2022-06-30 10:49 UTC, HaykAvagyan1 commented on src/examiner/components/ViewHoverButtons.vue
> +        <svg
Again, don't inline SVGs, use an image tag for these two button icons unless you need to modify SVG properties on runtime.

2022-06-30 10:49 UTC, HaykAvagyan1 commented on src/examiner/components/ImagesInStoryPreview.vue
> +  top: v-bind("props.obj.y * 600/570+'px'");
If you need different height for each of them add a `height` prop.

2022-06-30 10:49 UTC, HaykAvagyan1 commented on src/viewer/components/NestedImages.vue
> +      :class="{ chosed: show_assets }"
chosen*

2022-06-30 11:39 UTC, vrezhMik commented on src/examiner/components/ViewHoverButtons.vue
> +        <svg
Changed

2022-06-30 11:39 UTC, vrezhMik commented on src/examiner/components/BoardOverviewButton.vue
> +      <svg
Done

2022-06-30 11:41 UTC, vrezhMik commented on src/examiner/components/StoryPreview.vue
> +<script setup>
have no idea

2022-06-30 12:04 UTC, vrezhMik commented on src/examiner/components/ImagesInViewBoard.vue
> +  top: v-bind("props.obj.y*263/565+'px'");
I have removed ImagesInStoryPreview component. It is using ImagesInViewBoard component only now.
Fixed their positioning as well

2022-06-30 13:07 UTC, HaykAvagyan1 requested changes
Looks good, couple of notes and it's ready to merge.
Reword the last commit message(you can turn your current title into a description and write a more general title for it like `Refactor code, remove inline SVGs, etc.`) Positioning is still a little off when you compare preview mode and edit mode, so don't include that in the commit message. Also reword `CR changes` commit with a new title and description, you are adding 7 completely new files and most of your changes aren't related to CR.

2022-06-30 14:00 UTC, HaykAvagyan1 requested changes
Please reword `Refactoring and styling changes` commit again. Be more descriptive, for example "Refactor code, add preview buttons and panels for examiner, add examiner view" and so on. Also squash the last two commits together and it's ready to merge.

2022-06-30 14:14 UTC, HaykAvagyan1 approved these changes
Looks good to me.

2022-07-01 08:36 UTC, merged